profiles:
  - production

exclude_paths:
  - .ansible/
  - collections/ansible_collections/**/molecule/**
  - test/

skip_list:
  # Be pragmatic initially; tighten over time
  - var-naming
  - fqcn-builtins

parseable: true

