extends: default

ignore: |
  .ansible/**
  .github/**
  test/**
  collections/ansible_collections/**/molecule/**
  tasklist.yml
  group_vars/**
  roles/**

rules:
  document-start: disable
  line-length:
    max: 300
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  empty-lines:
    max: 1
    level: warning
  braces:
    max-spaces-inside: 1
  commas: disable
  truthy:
    level: warning
  comments:
    min-spaces-from-content: 1
    ignore-shebangs: true
  comments-indentation: false
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
