extends: default

ignore: |
  .ansible/**
  .github/**
  test/**
  collections/ansible_collections/**/molecule/**
  tasklist.yml
  group_vars/**
  roles/**

rules:
  document-start: disable
  line-length:
    max: 300
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  empty-lines:
    max: 1
    level: warning
  braces: disable
  commas: disable
  truthy:
    level: warning
