- name: Monitor | Collect replication info via module (feature-flagged)
  vars:
    suffix: "{{ item }}"
  directories.ds.ds_repl_info:
    instance: "{{ dirsrv_repl_this_node.instance }}"
    suffix: "{{ suffix }}"
  register: dirsrv_repl_info_results
  loop: "{{ dirsrv_repl_suffixes }}"
  changed_when: false
  failed_when: false
  when: dirsrv_repl_use_modules | bool

- name: Monitor | Show module info (concise)
  ansible.builtin.debug:
    msg: >-
      suffix={{ item.item }} enabled={{ item.replica.enabled | default(None) }}
      agmts={{ (item.agreements | map(attribute='host') | list) | default([]) }}
  loop: "{{ dirsrv_repl_info_results.results | default([]) }}"
  when:
    - dirsrv_repl_use_modules | bool

- name: Monitor | Write module info snapshots (test-only)
  vars:
    suffix: "{{ item.item }}"
    __snap_dir: "{{ [dirsrv_artifact_root_effective | default([playbook_dir, '.ansible', 'artifacts'] | path_join), inventory_hostname] | path_join }}"
  ansible.builtin.copy:
    content: "{{ {'host': inventory_hostname, 'suffix': suffix, 'replica': item.replica, 'agreements': item.agreements} | to_nice_json }}"
    dest: "{{ [__snap_dir, 'repl-info-' ~ (suffix | regex_replace('[^A-Za-z0-9_.-]','_')) ~ '.json'] | path_join }}"
    mode: "0640"
  connection: local
  delegate_to: localhost
  become: false
  loop: "{{ dirsrv_repl_info_results.results | default([]) }}"
  when:
    - dirsrv_repl_use_modules | bool
    - dirsrv_debug | bool

- name: Monitor | replication monitor snapshot (fallback)
  ansible.builtin.command: >-
    dsconf -D "{{ dirsrv_dm_dn }}" -w "{{ dirsrv_password }}" {{ dirsrv_repl_conn_url }}
    replication monitor
  register: dirsrv_repl_monitor
  changed_when: false
  failed_when: false
  no_log: "{{ not (dirsrv_debug | default(false) | bool) }}"
  when: not dirsrv_repl_use_modules | bool

- name: Monitor | Show monitor snapshot (concise) (fallback)
  ansible.builtin.debug:
    var: dirsrv_repl_monitor.stdout
  when:
    - not dirsrv_repl_use_modules | bool
    - dirsrv_repl_monitor.stdout is defined

- name: Monitor | Agreement status per local agreements (fallback)
  ansible.builtin.command: >-
    dsconf -D "{{ dirsrv_dm_dn }}" -w "{{ dirsrv_password }}" {{ dirsrv_repl_conn_url }}
    repl-agmt status --suffix "{{ item_suffix }}" {{ item_agmt.name }}
  vars:
    item_suffix: "{{ item.0.key }}"
    item_agmt: "{{ item.1 }}"
  register: dirsrv_repl_status
  changed_when: false
  failed_when: false
  no_log: "{{ not (dirsrv_debug | default(false) | bool) }}"
  with_subelements:
    - "{{ dirsrv_repl_agreements | dict2items }}"
    - value
  when:
    - not dirsrv_repl_use_modules | bool
    - item_agmt.from == inventory_hostname

- name: Monitor | ds-replcheck (optional)
  when: dirsrv_repl_run_replcheck | bool
  block:
    - name: Monitor | Determine ds-replcheck availability
      ansible.builtin.command: which ds-replcheck
      register: rhds_replcheck_which
      changed_when: false
      ignore_errors: true

    - name: Monitor | Warn when ds-replcheck is unavailable
      ansible.builtin.debug:
        msg: ds-replcheck not installed; skipping replication check.
      when: rhds_replcheck_which.rc != 0

    - name: Monitor | Run ds-replcheck in requested mode
      ansible.builtin.command: >-
        {% if dirsrv_replcheck_mode == 'state' %}
        ds-replcheck state
        {% elif dirsrv_replcheck_mode == 'online' %}
        ds-replcheck online
        {% else %}
        ds-replcheck offline --supplier "{{ dirsrv_replcheck_offline_ldif.supplier_ldif }}" --consumer "{{ dirsrv_replcheck_offline_ldif.consumer_ldif }}"
        {% endif %}
      register: rhds_replcheck_run
      changed_when: false
      failed_when: rhds_replcheck_run.rc != 0
      ignore_errors: true
      when: rhds_replcheck_which.rc == 0

    - name: Monitor | Show replcheck output
      ansible.builtin.debug:
        var: rhds_replcheck_run.stdout
      when:
        - rhds_replcheck_run is defined
        - rhds_replcheck_run.rc == 0

    - name: Monitor | Warn when ds-replcheck run fails
      ansible.builtin.debug:
        msg: "ds-replcheck failed: {{ rhds_replcheck_run.stderr }}"
      when:
        - rhds_replcheck_run is defined
        - rhds_replcheck_run.rc != 0
