---
# Lightweight monitoring using module-based introspection (no CLI fallbacks)

- name: Monitoring | Gather replication info
  vars:
    suffix: "{{ item }}"
  directories.ds.ds_repl_info:
    instance: "{{ dirsrv_repl_this_node.instance }}"
    suffix: "{{ suffix }}"
  register: monitoring_repl_info
  loop: "{{ dirsrv_repl_suffixes }}"
  changed_when: false
  failed_when: false

- name: Monitoring | Save info snapshots (optional)
  vars:
    suffix: "{{ item.item }}"
    __snap_dir: "{{ [dirsrv_artifact_root_effective | default([playbook_dir, '.ansible', 'artifacts'] | path_join), inventory_hostname] | path_join }}"
  ansible.builtin.copy:
    content: "{{ {'host': inventory_hostname, 'suffix': suffix, 'replica': item.replica, 'agreements': item.agreements} | to_nice_json }}"
    dest: "{{ [__snap_dir, 'monitoring-info-' ~ (suffix | regex_replace('[^A-Za-z0-9_.-]','_')) ~ '.json'] | path_join }}"
    mode: "0640"
  connection: local
  delegate_to: localhost
  become: false
  loop: "{{ monitoring_repl_info.results | default([]) }}"
  when: dirsrv_debug | bool

- name: Monitoring | Summary
  ansible.builtin.debug:
    msg: >-
      suffix={{ item.item }} enabled={{ item.replica.enabled | default(None) }}
      agmts={{ (item.agreements | map(attribute='host') | list) | default([]) }}
      summary={{ item.summary | default({}) }}
  loop: "{{ monitoring_repl_info.results | default([]) }}"
