## Expects vars: retry_suffix, retry_agmt

- name: Retry | Initialize agreement via module (with wait)
  directories.ds.ds_repl_init:
    instance: "{{ dirsrv_repl_this_node.instance }}"
    suffix: "{{ retry_suffix }}"
    agreement: "{{ retry_agmt }}"
    conn_url: "{{ dirsrv_repl_conn_url }}"
    dm_dn: "{{ dirsrv_dm_dn }}"
    dm_pw: "{{ dirsrv_password }}"
    timeout: "{{ rhds_repl_retry_timeout | default(300) }}"
    poll_interval: "{{ rhds_repl_wait_delay | default(3) }}"
  throttle: 1
