---
- name: Tuning | Set replication release-timeout per suffix
  ansible.builtin.command: >-
    dsconf -D "{{ dirsrv_dm_dn }}" -w "{{ dirsrv_password }}" {{ dirsrv_repl_conn_url }}
    replication set --suffix "{{ item }}" --repl-release-timeout {{ dirsrv_repl_release_timeout | int }}
  register: dirsrv_repl_timeout
  changed_when: >-
    dirsrv_repl_timeout.rc == 0 and (
      'updated' in (dirsrv_repl_timeout.stdout | lower | default('')) or
      'modified' in (dirsrv_repl_timeout.stdout | lower | default(''))
    )
  failed_when: false
  no_log: true
  loop: "{{ dirsrv_repl_suffixes }}"
  when: dirsrv_repl_set_release_timeout | bool and (not ansible_check_mode)

- name: Tuning | Configure changelog purge (max-age) per suffix
  ansible.builtin.command: >-
    dsconf -D "{{ dirsrv_dm_dn }}" -w "{{ dirsrv_password }}" {{ dirsrv_repl_conn_url }}
    replication set-changelog --suffix "{{ item }}" --max-age {{ dirsrv_repl_changelog.max_age }}
  register: dirsrv_repl_purge
  changed_when: >-
    dirsrv_repl_purge.rc == 0 and (
      'updated' in (dirsrv_repl_purge.stdout | lower | default('')) or
      'modified' in (dirsrv_repl_purge.stdout | lower | default(''))
    )
  failed_when: false
  no_log: true
  loop: "{{ dirsrv_repl_suffixes }}"
  when: dirsrv_repl_changelog.purge_enabled | bool and (not ansible_check_mode)

- name: Tuning | Changelog encryption workflow note
  ansible.builtin.debug:
    msg: >-
      "Encryption requested (dirsrv_repl_changelog.encrypt=true). Implement stop→enable→verify→start per site policy. Skipping automatic change for safety."
    warn: true
  when: dirsrv_repl_changelog.encrypt | bool
