---
- name: Wait | Skip if no agreements
  ansible.builtin.meta: noop
  when: dirsrv_repl_agreements | length == 0

- name: Wait | Compute local dsconf URL when missing
  ansible.builtin.set_fact:
    dirsrv_repl_conn_url: >-
      {{
        (dirsrv_ldapi_uri | default(''))
        if (dirsrv_ldapi_uri | default('') | length > 0)
        else (
          dirsrv_repl_conn_url | default(
            (
              (dirsrv_repl_nodes[inventory_hostname].protocol | lower) ~ '://' ~
              dirsrv_repl_nodes[inventory_hostname].host ~ ':' ~
              dirsrv_repl_nodes[inventory_hostname].port
            ) if (dirsrv_repl_nodes is defined and dirsrv_repl_nodes[inventory_hostname] is defined) else ''
          )
        )
      }}

- name: Wait | Agreements healthy (with snapshot on failure)
  block:
    - name: Wait | Until each local agreement is healthy
      vars:
        agmt_suffix: "{{ item.0.key }}"
        agmt: "{{ item.1 }}"
        tries: "{{ rhds_repl_wait_max_retries | default(120) }}"
        delay: "{{ rhds_repl_wait_delay | default(3) }}"
      ansible.builtin.command:
        argv:
          - dsconf
          - -D
          - "{{ dirsrv_dm_dn }}"
          - -w
          - "{{ dirsrv_password }}"
          - "{{ dirsrv_repl_conn_url }}"
          - -j
          - repl-agmt
          - status
          - --suffix
          - "{{ agmt_suffix }}"
          - "{{ agmt.name }}"
      register: out
      no_log: true
      changed_when: false
      failed_when: false
      until: >-
        (
          out.stdout is search('"error"\s*:\s*0') or
          out.stdout is search('"initialized"\s*:\s*true') or
          out.stdout is search('successfully initialized')
        )
        and not (out.stdout | lower | default('')) is search('in progress')
      retries: "{{ tries }}"
      delay: "{{ delay }}"
      with_subelements:
        - "{{ dirsrv_repl_agreements | dict2items }}"
        - value
      when:
        - agmt.from == inventory_hostname
  rescue:
    - name: Snapshot | Ensure local artifacts dir exists (controller)
      ansible.builtin.file:
        path: "{{ [dirsrv_artifact_root_effective, inventory_hostname] | path_join }}"
        state: directory
        mode: "0750"
      connection: local
      delegate_to: localhost
      become: false
      when: dirsrv_debug | bool
    - name: Snapshot | Agreements wait last results (test-only)
      vars:
        res: "{{ item }}"
        suffix: "{{ item.item.0.key | default('') }}"
        agree: "{{ item.item.1.name | default('') }}"
        __snap_dir: "{{ [dirsrv_artifact_root_effective, inventory_hostname] | path_join }}"
        __raw_cmd: "{{ (res.cmd | default('')) | string }}"
        __san_cmd: "{{ __raw_cmd | regex_replace('(?i)(-w) +[^ ]+','-w ****') }}"
        __parts: "{{ (res.delta | default('0:0:0.0')) | regex_findall('([0-9]+)') }}"
        __dur_ms: "{{ (__parts[0] | default('0') | int) * 3600000 + (__parts[1] | default('0') | int) * 60000 + (__parts[2] | default('0') | int) * 1000 + ((__parts[3] | default('0') | int) // 1000) }}"
      ansible.builtin.copy:
        content: |
          {{ {
              'host': inventory_hostname,
              'step': 'wait-green-' ~ (agree | regex_replace('[^A-Za-z0-9_.-]','_')) ~ '-' ~ (suffix | regex_replace('[^A-Za-z0-9_.-]','_')),
              'ts': (ansible_date_time.iso8601_micro | default("%Y-%m-%dT%H:%M:%SZ" | strftime)),
              'argv_redacted': __san_cmd,
              'rc': res.rc | default(-1),
              'stdout_excerpt': (res.stdout | default(''))[:2048],
              'stderr_excerpt': (res.stderr | default(''))[:2048],
              'duration_ms': __dur_ms
            } | to_nice_json }}
        dest: "{{ [__snap_dir, 'cmd-wait-green-' ~ (agree | regex_replace('[^A-Za-z0-9_.-]','_')) ~ '-' ~ (suffix | regex_replace('[^A-Za-z0-9_.-]','_')) ~ '.json'] | path_join }}"
        mode: "0640"
      connection: local
      delegate_to: localhost
      become: false
      loop: "{{ out.results | default([]) }}"
      when: dirsrv_debug | bool
    - name: Fail | Agreements did not reach healthy state
      ansible.builtin.fail:
        msg: "Agreements not healthy; see .ansible/artifacts/<run>/<host>/cmd-wait-green-*.json snapshots for details"
