---
- name: Wait | Skip if no agreements
  ansible.builtin.debug:
    msg: "No replication agreements defined; skipping wait"
  when: (dirsrv_repl_agreements | length | int) == 0

- name: Wait | Compute local connection URL when missing
  ansible.builtin.set_fact:
    dirsrv_repl_conn_url: >-
      {{
        (dirsrv_ldapi_uri | default(''))
        if (dirsrv_ldapi_uri | default('') | length > 0)
        else (
          dirsrv_repl_conn_url | default(
            (
              (dirsrv_repl_nodes[inventory_hostname].protocol | lower) ~ '://' ~
              dirsrv_repl_nodes[inventory_hostname].host ~ ':' ~
              dirsrv_repl_nodes[inventory_hostname].port
            ) if (dirsrv_repl_nodes is defined and dirsrv_repl_nodes[inventory_hostname] is defined) else ''
          )
        )
      }}

- name: Wait | Ensure artifact root fact (fallback)
  ansible.builtin.set_fact:
    dirsrv_artifact_root_effective: "{{ [playbook_dir, '.ansible', 'artifacts'] | path_join }}"
  when: dirsrv_artifact_root_effective is not defined

- name: Wait | Compute agreements originating from this node
  ansible.builtin.set_fact:
    _dirsrv_my_agreements: >-
      {{
        (dirsrv_repl_agreements | default({}))
          | dict2items
          | map(attribute='value')
          | flatten
          | selectattr('from','equalto', inventory_hostname)
          | list
      }}

- name: Wait | Agreements healthy via module
  directories.ds.ds_repl_wait:
    instance: "{{ dirsrv_repl_this_node.instance }}"
    suffix: "{{ item }}"
    all: true
    stale_seconds: "{{ dirsrv_repl_wait_stale_seconds | default(300) }}"
    steady_ok_polls: "{{ dirsrv_repl_wait_steady_ok_polls | default(3) }}"
    poll_interval: "{{ dirsrv_repl_wait_delay | default(3) }}"
    timeout: "{{ dirsrv_repl_wait_timeout | default(900) }}"
    require:
      configured: true
      working: true
      finished: "{{ dirsrv_repl_wait_require_finished | default(false) }}"
    timeouts:
      configured: "{{ dirsrv_repl_wait_timeout_configured | default(20) }}"
      start: "{{ dirsrv_repl_wait_timeout_start | default(30) }}"
      done: "{{ dirsrv_repl_wait_timeout_done | default(120) }}"
    debug: "{{ dirsrv_debug | default(false) }}"
    log_every: "{{ 1 if (dirsrv_debug | default(false)) else 5 }}"
  loop: "{{ dirsrv_repl_suffixes }}"
  when:
    - dirsrv_repl_suffixes | length > 0
    - (_dirsrv_my_agreements | length) > 0
