---
- name: Ensure local artifact directory exists for this source
  ansible.builtin.file:
    path: "{{ dsm_artifact_root }}/{{ inventory_hostname }}"
    state: directory
    mode: "0750"
  connection: local
  delegate_to: localhost

- name: Stop LDAP instance
  ansible.builtin.systemd:
    name: "dirsrv@{{ dsm_instance }}"
    state: stopped

- name: Dump LDAP instance to LDIF
  ansible.builtin.command:
    argv:
      - /sbin/dsctl
      - "{{ dsm_instance }}"
      - db2ldif
      - "{{ item }}"
      - "{{ dsm_base_varldif }}/migration-{{ item }}.ldif"
  loop: "{{ dsm_backends.keys() | list }}"
  changed_when: false

- name: Fetch the LDIF dumps
  ansible.builtin.fetch:
    dest: "{{ dsm_artifact_root }}/{{ inventory_hostname }}/migration-{{ item }}.ldif"
    flat: true
    src: "{{ dsm_base_varldif }}/migration-{{ item }}.ldif"
  loop: "{{ dsm_backends.keys() | list }}"

- name: Fix permissions on LDIF dumps
  ansible.builtin.file:
    path: "{{ dsm_artifact_root }}/{{ inventory_hostname }}/migration-{{ item }}.ldif"
    mode: "0640"
  connection: local
  delegate_to: localhost
  loop: "{{ dsm_backends.keys() | list }}"

- name: Create archive of instance config
  ansible.builtin.command:
    argv:
      - /bin/tar
      - cjf
      - "{{ dsm_tempdir }}/dirsrv_slapd-{{ dsm_instance }}.tar.bz2"
      - "{{ dsm_base_config }}"
  changed_when: false

- name: Fetch the config archive
  ansible.builtin.fetch:
    src: "{{ dsm_tempdir }}/dirsrv_slapd-{{ dsm_instance }}.tar.bz2"
    dest: "{{ dsm_artifact_root }}/{{ inventory_hostname }}/"
    flat: true

- name: Fix permissions on config archive
  ansible.builtin.file:
    path: "{{ dsm_artifact_root }}/{{ inventory_hostname }}/dirsrv_slapd-{{ dsm_instance }}.tar.bz2"
    mode: "0640"
  connection: local
  delegate_to: localhost

- name: Start LDAP instance
  ansible.builtin.systemd:
    name: "dirsrv@{{ dsm_instance }}"
    state: started

- name: Remove archive of instance config on source
  ansible.builtin.file:
    path: "{{ dsm_tempdir }}/dirsrv_slapd-{{ dsm_instance }}.tar.bz2"
    state: absent
