---
# Central default suffix for directory data (override per environment if needed)
dirsrv_default_suffix: "dc=example,dc=com"

# Backends configured for migration/import/export
dirsrv_backends:
  userroot:
    suffix: "{{ dirsrv_default_suffix }}"

# Replication suffixes aligned to the global default
dirsrv_repl_suffixes:
  - "{{ dirsrv_default_suffix }}"
