version: "3.8"

networks:
  dsnet:
    driver: bridge
    name: dsnet

services:
  ds-s1:
    image: quay.io/389ds/dirsrv:latest
    container_name: ds-s1
    hostname: s1.dsnet.test
    environment:
      - DS_DM_PASSWORD=password
      - DS_SUFFIX_NAME=dc=example,dc=com
      - DS_PORT=389
    networks:
      dsnet:
        aliases: [ds-s1, s1.dsnet.test]
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket -s base -b '' 1.1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 50
    volumes:
      - type: bind
        source: ../testdata/example.ldif
        target: /root/example.ldif
      # Explicit DS instance persistence (config/data/certs/logs)
      - type: bind
        source: ../.ansible/containers/ds-s1/etc-dirsrv-slapd-localhost
        target: /etc/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-s1/var-lib-dirsrv-slapd-localhost
        target: /var/lib/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-s1/etc-dirsrv-slapd-localhost-certs
        target: /etc/dirsrv/slapd-localhost/certs:Z
      - type: bind
        source: ../.ansible/containers/ds-s1/var-log-dirsrv-slapd-localhost
        target: /var/log/dirsrv/slapd-localhost:Z

  ds-s2:
    image: quay.io/389ds/dirsrv:latest
    container_name: ds-s2
    hostname: s2.dsnet.test
    environment:
      - DS_DM_PASSWORD=password
      - DS_SUFFIX_NAME=dc=example,dc=com
      - DS_PORT=389
    networks:
      dsnet:
        aliases: [ds-s2, s2.dsnet.test]
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket -s base -b '' 1.1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 50
    volumes:
      - type: bind
        source: ../.ansible/containers/ds-s2/etc-dirsrv-slapd-localhost
        target: /etc/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-s2/var-lib-dirsrv-slapd-localhost
        target: /var/lib/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-s2/etc-dirsrv-slapd-localhost-certs
        target: /etc/dirsrv/slapd-localhost/certs:Z
      - type: bind
        source: ../.ansible/containers/ds-s2/var-log-dirsrv-slapd-localhost
        target: /var/log/dirsrv/slapd-localhost:Z

  ds-c1:
    image: quay.io/389ds/dirsrv:latest
    container_name: ds-c1
    hostname: c1.dsnet.test
    environment:
      - DS_DM_PASSWORD=password
      - DS_SUFFIX_NAME=dc=example,dc=com
      - DS_PORT=389
    networks:
      dsnet:
        aliases: [ds-c1, c1.dsnet.test]
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket -s base -b '' 1.1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 50
    volumes:
      - type: bind
        source: ../.ansible/containers/ds-c1/etc-dirsrv-slapd-localhost
        target: /etc/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-c1/var-lib-dirsrv-slapd-localhost
        target: /var/lib/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-c1/etc-dirsrv-slapd-localhost-certs
        target: /etc/dirsrv/slapd-localhost/certs:Z
      - type: bind
        source: ../.ansible/containers/ds-c1/var-log-dirsrv-slapd-localhost
        target: /var/log/dirsrv/slapd-localhost:Z

  ds-c2:
    image: quay.io/389ds/dirsrv:latest
    container_name: ds-c2
    hostname: c2.dsnet.test
    environment:
      - DS_DM_PASSWORD=password
      - DS_SUFFIX_NAME=dc=example,dc=com
      - DS_PORT=389
    networks:
      dsnet:
        aliases: [ds-c2, c2.dsnet.test]
    healthcheck:
      test: ["CMD-SHELL", "ldapsearch -Y EXTERNAL -H ldapi://%2Fdata%2Frun%2Fslapd-localhost.socket -s base -b '' 1.1 >/dev/null || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 50
    volumes:
      - type: bind
        source: ../.ansible/containers/ds-c2/etc-dirsrv-slapd-localhost
        target: /etc/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-c2/var-lib-dirsrv-slapd-localhost
        target: /var/lib/dirsrv/slapd-localhost:Z
      - type: bind
        source: ../.ansible/containers/ds-c2/etc-dirsrv-slapd-localhost-certs
        target: /etc/dirsrv/slapd-localhost/certs:Z
      - type: bind
        source: ../.ansible/containers/ds-c2/var-log-dirsrv-slapd-localhost
        target: /var/log/dirsrv/slapd-localhost:Z

volumes: {}
