all:
  children:
    suppliers:
      hosts:
        s1.dsnet.test:
          replica_id: 1001
          ldap_port: 389
          ldaps_port: 636
          instance_name: "localhost"
        s2.dsnet.test:
          replica_id: 1002
          ldap_port: 389
          ldaps_port: 636
          instance_name: "localhost"
    consumers:
      hosts:
        c1.dsnet.test:
          replica_id: 2001
          ldap_port: 389
          ldaps_port: 636
          instance_name: "localhost"
        c2.dsnet.test:
          replica_id: 2002
          ldap_port: 389
          ldaps_port: 636
          instance_name: "localhost"
