---
# Minimal TLS enablement role per design. Guarded to be no-op unless inputs are provided.

- name: TLS | Assert inputs provided (guarded)
  ansible.builtin.assert:
    that:
      - (dirsrv_tls_ca_crt | default('')) | length > 0
      - (dirsrv_tls_server_crt | default('')) | length > 0
    fail_msg: "Provide TLS inputs: dirsrv_tls_ca_crt (CA PEM), dirsrv_tls_server_crt (server PEM)"
  when: dirsrv_tls_enabled | default(false)

- name: TLS | Import CA certificate (trust CT,C,C)
  ansible.builtin.command:
    argv:
      - certutil
      - -A
      - -d
      - "/etc/dirsrv/slapd-{{ dirsrv_instance | default('localhost') }}"
      - -n
      - "lab-CA"
      - -t
      - "CT,C,C"
      - -a
      - -i
      - "{{ dirsrv_tls_ca_crt }}"
  register: tls_add_ca
  changed_when: tls_add_ca.rc == 0
  failed_when: false
  when: dirsrv_tls_enabled | default(false)

- name: TLS | Import server certificate as primary
  ansible.builtin.command:
    argv:
      - dsconf
      - "{{ dirsrv_instance | default('localhost') }}"
      - security
      - certificate
      - add
      - --file
      - "{{ dirsrv_tls_server_crt }}"
      - --name
      - "{{ inventory_hostname }}"
      - --primary-cert
  register: tls_add_srv
  changed_when: tls_add_srv.rc == 0
  failed_when: false
  when: dirsrv_tls_enabled | default(false)

- name: TLS | Enable secure port 636
  ansible.builtin.command:
    argv:
      - dsconf
      - "{{ dirsrv_instance | default('localhost') }}"
      - config
      - replace
      - "nsslapd-securePort=636"
  register: tls_sec_port
  changed_when: tls_sec_port.rc == 0
  failed_when: false
  when: dirsrv_tls_enabled | default(false)

- name: TLS | Set certificate nickname (nsSSLPersonalitySSL)
  ansible.builtin.command:
    argv:
      - dsconf
      - "{{ dirsrv_instance | default('localhost') }}"
      - config
      - replace
      - "nsSSLPersonalitySSL={{ inventory_hostname }}"
  register: tls_set_nick
  changed_when: tls_set_nick.rc == 0
  failed_when: false
  when: dirsrv_tls_enabled | default(false)

- name: TLS | Restart instance to apply settings
  ansible.builtin.command:
    argv:
      - dsctl
      - "{{ dirsrv_instance | default('localhost') }}"
      - restart
  register: tls_restart
  changed_when: tls_restart.rc == 0
  failed_when: false
  when: dirsrv_tls_enabled | default(false)

