---
# Default variables for DSM role.
# Override via inventory/group_vars. Secrets (e.g., dsm_password) must come from Ansible Vault.
# Note: Package installation is handled by a separate role; this role assumes
# required packages (e.g., 389-ds-base) are already present on targets.

dsm_instance: dir
dsm_tempdir: /var/tmp

dsm_base_var: "/var/lib/dirsrv/slapd-{{ dsm_instance }}"
dsm_base_varldif: "/var/lib/dirsrv/slapd-{{ dsm_instance }}/ldif"
dsm_base_config: "/etc/dirsrv/slapd-{{ dsm_instance }}"
dsm_base_log: "/var/log/dirsrv/slapd-{{ dsm_instance }}"
dsm_dse_ldif: "etc/dirsrv/slapd-{{ dsm_instance }}/dse.ldif"

dsm_backends:
  userroot:
    suffix: "o=example"


# Local artifact staging for migrations (on controller)
dsm_artifact_root: "{{ playbook_dir }}/.ansible/artifacts"

# Source → Target host mapping (override in group_vars)
# Example:
# dsm_host_map:
#   rhds11.example.com: rhds12.example.com
dsm_host_map: {}

# Cleanup patterns for configuration DSE LDIF (multi-line regex allowed)
# Each item: { name: <id>, regexp: <pattern>, replace: <string default ''> }
dsm_cleanup_patterns_dse:
  - name: remove_replication_agreements
    regexp: "(?ms)^dn: cn=replica,.*?(?=^dn: |\\Z)"
    replace: ""

# Cleanup patterns for exported backend LDIFs (applied on target before import)
dsm_cleanup_patterns_data: []
