name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible-lint yamllint ruff

    - name: Run ansible-lint
      run: ansible-lint roles/ site.yml --exclude collections/

    - name: Run yamllint
      run: yamllint --exclude-dir=collections .

    - name: Run ruff
      run: ruff check .

    - name: Ansible syntax check
      run: ansible-playbook --syntax-check site.yml

    - name: Check YAML formatting
      run: |
        # Ensure YAML files are properly formatted
        find . -name "*.yml" -o -name "*.yaml" | xargs -I {} sh -c 'echo "Checking {}"; python -c "import yaml; yaml.safe_load(open(\"{}\"))" || exit 1'